name: CI
on: [push, pull_request]

jobs:
  test:
    name: Dub Test
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        dc: [dmd-2.095.1]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1.0.5
        with:
          compiler: ${{ matrix.dc }}

      - name: "Windows: Run tests"
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          set
          :: set up MSVC environment - x64 for LDC, x86 for DMD
          set MSVC_ARCH=x64
          if "%DC%" == "dmd" set MSVC_ARCH=x86
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=%MSVC_ARCH% || exit /b
          :: test
          dub -q test -- ~@tup

  bootstrap:
    name: Bootstrap
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        dc: [dmd-2.095.1]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: "Windows: Install ninja"
        if: runner.os == 'Windows'
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1.0.5
        with:
          compiler: ${{ matrix.dc }}
      - name: Set OS-specific SCRIPT_CMD environment variable
        run: |
          if [[ '${{ runner.os }}' == 'Windows' ]]; then
            echo "SCRIPT_CMD=./bootstrap.bat" >> $GITHUB_ENV
          else
            echo "SCRIPT_CMD=./bootstrap.sh" >> $GITHUB_ENV
          fi

      - name: Bootstrap with DC=${{ env.DC }}
        run: ${{ env.SCRIPT_CMD }}
